// import { exact } from "prop-types";
import React, { useEffect } from "react";
// import { useLocation } from 'react-router-dom';
// import Auth from '../utils/auth';
import LeftNav from '../components/LeftNav';

export default function Home() {

  
  return(
    // add padding for edges
    <section class="topic-container"> 
      {/* <div className="left-bar">
        <LeftNav/>
      </div> */}
      <div className="middle-bar">
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
        Feed<br/>
      </div>
      <div className="right-bar">
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>
        Follows<br/>

      </div>
    </section>
  );
};